image: "ghcr.io/cirruslabs/flutter:stable"

stages:
  - analyze_and_test
  - preview
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .pub-cache/global_packages
    - export PATH="$PATH":"$HOME/.pub-cache/bin"

code_quality:
  stage: analyze_and_test
  before_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter pub global activate dart_code_metrics  
  script:
    - metrics lib -r codeclimate > gl-code-quality-report.json
  artifacts:
    when: always
    reports:
      codequality: gl-code-quality-report.json
  only:
    - merge_requests

analyze:
  stage: analyze_and_test
  before_script:
    - touch .env
  script:
    - flutter analyze --fatal-infos --fatal-warnings
  only:
    - merge_requests

test:
  stage: analyze_and_test
  before_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter pub global activate junitreport
    - touch .env
  script:    
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: "${CI_COMMIT_REF_NAME}_coverage"
    paths:
      - coverage/
    reports:
      junit: report.xml

deploy-preview:
  stage: preview
  image: node:bookworm
  script:
    - npm install --global vercel
    - touch .env
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN > deployment-url.txt
  after_script:
    - echo "🔝🔝 Deploying to Vercel... 🚀"
    - DEPLOYMENT_URL_CONTENT=$(cat deployment-url.txt)
    - |
      NEW_LINE=$'\n'
      JOB_URL="$CI_PROJECT_URL/-/jobs/$CI_JOB_ID"
      if [ "$CI_JOB_STATUS" == "success" ]; then
       BOT_MESSAGE="### ✔️ 🔥🔥 DEPLOY DE PREVIEW PRONTO !! 🔥🔥 ✔️${NEW_LINE}🚀🚀🚀 URL: $DEPLOYMENT_URL_CONTENT 👻👻"
      else
       BOT_MESSAGE="### ✖️ Oh no.. 😵 O deploy de preview falhou 😵 ✖️${NEW_LINE} Veja os [logs do job]($JOB_URL) e descubra o que aconteceu."
      fi
      curl -X POST \
        -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
        --form "body=$BOT_MESSAGE" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"
    - rm deployment-url.txt
  only:
    - merge_requests
  allow_failure: true
  when: manual

deploy_dev:
  stage: deploy
  script:
    - echo "🔝🔝 Deploying to DEV environment... 🚀"
    - touch .env
    - flutter pub get
    - flutter build web
    - mkdir -p /app/dev/usr/share/nginx/html
    - cp -r build/web/* /app/dev/usr/share/nginx/html/
    - ls -al /app/dev/usr/share/nginx/html
  artifacts:
    paths:
      - build/web/
  environment:
    name: dev
  only:
    - develop