services:
  # Runner
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  # Runner Register
  gitlab-runner-register:
    image: gitlab/gitlab-runner:latest
    restart: "no"
    container_name: gitlab-runner-register
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_EXECUTOR=docker
    command: 
      - register 
      - --non-interactive
      - --locked=false
      - --url=${CI_SERVER_URL}
      - --registration-token=${REGISTRATION_TOKEN}
      - --executor=docker
      - --docker-image="cirruslabs/flutter:stable"
      - --description="gitlab-runner"
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner

  # PROD Frontend
  nginx-prod:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "80:80"
    volumes:
      - prod-web-content:/usr/share/nginx/html:ro
    environment:
      - ENV=PROD
    depends_on:
      - gitlab-runner
      - s3-sync-prod

  # s3-sync-prod:
  #   image: amazon/aws-cli
  #   container_name: s3-sync-prod
  #   volumes:
  #     - prod-web-content:/usr/share/nginx/html
  #   environment:
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  #   command: ["/bin/sh", "./sync-s3.sh ${AWS_S3_BUCKET_NAME} prod"]
    
  # DEV Frontend
  nginx-dev:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "9000:80"
    volumes:
      - dev-web-content:/usr/share/nginx/html:ro
    environment:
      - ENV=DEV
    depends_on:
      - gitlab-runner
      - s3-sync-dev

  # s3-sync-dev:
  #   image: amazon/aws-cli
  #   container_name: s3-sync-dev
  #   volumes:
  #     - dev-web-content:/usr/share/nginx/html
  #   environment:
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  #   command: ["/bin/sh", "./sync-s3.sh ${AWS_S3_BUCKET_NAME} dev"]
