services:
  # Runner
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  # Runner Register
  gitlab-runner-register:
    image: gitlab/gitlab-runner:latest
    restart: "no"
    container_name: gitlab-runner-register
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_EXECUTOR=docker
    command: 
      - register 
      - --non-interactive
      - --locked=false
      - --url=${CI_SERVER_URL}
      - --registration-token=${REGISTRATION_TOKEN}
      - --executor=docker
      - --docker-image="cirruslabs/flutter:stable"
      - --description="gitlab-runner"
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner

  # PROD Frontend
  nginx-prod:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "80:80"
    volumes:
      - nginx-prod:/usr/share/nginx/html:ro
    environment:
      - ENV=PROD
    
  # DEV Frontend
  nginx-dev:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "9000:80"
    volumes:
      - nginx-dev:/usr/share/nginx/html:ro
    environment:
      - ENV=DEV
