name: turismo_rural_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  google_maps_flutter: ^2.6.0
  nested: any
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  lint: ^2.3.0

flutter:
  assets:
    - .env
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
  uses-material-design: true
