// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwGQfhvbJUgvL43noZelXt8De206z91Wo',
    appId: '1:168801725450:web:ebbc3c4e3b7489f81dc3f3',
    messagingSenderId: '168801725450',
    projectId: 'sao-chico-app',
    authDomain: 'sao-chico-app.firebaseapp.com',
    storageBucket: 'sao-chico-app.firebasestorage.app',
    measurementId: 'G-TEE5DJK6EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTHxQl9GreaRJu9JdZ-FA46ILZJBlj994',
    appId: '1:168801725450:android:5ab8e7a178c587ed1dc3f3',
    messagingSenderId: '168801725450',
    projectId: 'sao-chico-app',
    storageBucket: 'sao-chico-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFOo_BAfAuz1J6eH57xnqpr9RtMgPU_HI',
    appId: '1:168801725450:ios:cd04b62cf958ecf31dc3f3',
    messagingSenderId: '168801725450',
    projectId: 'sao-chico-app',
    storageBucket: 'sao-chico-app.firebasestorage.app',
    iosBundleId: 'com.example.turismoRuralFrontend',
  );
}
