// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7OgRANTSIeW5BG24JwHMCYeSdKEGhaE0',
    appId: '1:50025737160:web:a6b2d042ffb359ba436efd',
    messagingSenderId: '50025737160',
    projectId: 'turismo-rural-sao-chico',
    authDomain: 'turismo-rural-sao-chico.firebaseapp.com',
    storageBucket: 'turismo-rural-sao-chico.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_OWbWwhCTFCbqgkz-zxkqgm9Wt6t_7w',
    appId: '1:50025737160:android:5f6db666900396f6436efd',
    messagingSenderId: '50025737160',
    projectId: 'turismo-rural-sao-chico',
    storageBucket: 'turismo-rural-sao-chico.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPcz_vb3fbn5CCxY-N4KTODN9elvj7NKU',
    appId: '1:50025737160:ios:f723bc0be423739d436efd',
    messagingSenderId: '50025737160',
    projectId: 'turismo-rural-sao-chico',
    storageBucket: 'turismo-rural-sao-chico.appspot.com',
    iosBundleId: 'com.example.turismoRuralFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPcz_vb3fbn5CCxY-N4KTODN9elvj7NKU',
    appId: '1:50025737160:ios:f723bc0be423739d436efd',
    messagingSenderId: '50025737160',
    projectId: 'turismo-rural-sao-chico',
    storageBucket: 'turismo-rural-sao-chico.appspot.com',
    iosBundleId: 'com.example.turismoRuralFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7OgRANTSIeW5BG24JwHMCYeSdKEGhaE0',
    appId: '1:50025737160:web:039a1139e6d6216b436efd',
    messagingSenderId: '50025737160',
    projectId: 'turismo-rural-sao-chico',
    authDomain: 'turismo-rural-sao-chico.firebaseapp.com',
    storageBucket: 'turismo-rural-sao-chico.appspot.com',
  );
}
