#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(feat|fix|test|docs|style|refactor|perf|build|ci)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Please use 'type: message' format. Allowed types: feat, fix, test, docs, style, refactor, perf, build, ci." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,72}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi